name = input('Enter your name: ')
age = input('Enter your age: ')
# print(name)
print('Your name is ' + name + ' and you are ' + age + ' years old')
print(f'Your name is {name} and you are {age} years old')